# ========== Category References ========== #
all_categories = " 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 ",
all_ladies_categories = " 6 7 8 9 10 16 17 18 19 20 26 27 28 29 30 36 37 38 39 40 "
adult_ladies_categories = " 6 16 26 36 "
under_18_categories = " 2 3 4 5 7 8 9 10 12 13 14 15 17 18 19 20 22 23 24 25 27 28 29 30 32 33 34 35 37 38 39 40 "
under_18_ladies = " 7 17 27 37 "
under_16_categories = " 3 4 5 8 9 10 13 14 15 18 19 20 23 24 25 28 29 30 33 34 35 38 39 40 "
under_16_ladies = " 8 18 28 38 "
under_14_categories = " 4 5 9 10 14 15 19 20 24 25 29 30 34 35 39 40 "
under_14_ladies = " 9 19 29 39 "
under_12_categories = " 5 10 15 20 25 30 35 40 "
under_12_ladies = " 10 20 30 40 "
# ============= Create rounds ============= #
# ============== WA outdoor =============== #
Round.create!(name: "WA 1440 (Gentlemen)",
              indoor: false,
              organisation: "World Archery",
              max_hits: 144,
              max_score: 1440,
              arrows_per_end: 6,
              distance_1: "90m",
              face_1: 122,
              ends_1: 6,
              distance_2: "70m",
              face_2: 122,
              ends_2: 6,
              distance_3: "50m",
              face_3: 80,
              ends_3: 6,
              distance_4: "30m",
              face_4: 80,
              ends_4: 6,
              gmb_achievable: all_categories,
              mb_achievable: all_categories,
              bowman_achievable: all_categories,
              first_achievable: all_categories,
              second_achievable: all_categories,
              third_achievable: all_categories)

Round.create!(name: "WA 1440 (Ladies)",
              indoor: false,
              organisation: "World Archery",
              max_hits: 144,
              max_score: 1440,
              arrows_per_end: 6,
              distance_1: "70m",
              face_1: 122,
              ends_1: 6,
              distance_2: "60m",
              face_2: 122,
              ends_2: 6,
              distance_3: "50m",
              face_3: 80,
              ends_3: 6,
              distance_4: "30m",
              face_4: 80,
              ends_4: 6,
              gmb_achievable: adult_ladies_categories,
              mb_achievable: under_18_categories + adult_ladies_categories,
              bowman_achievable: under_18_categories + adult_ladies_categories,
              first_achievable: all_categories,
              second_achievable: all_categories,
              third_achievable: all_categories)

Round.create!(name: "Metric 1",
              indoor: false,
              organisation: "World Archery",
              max_hits: 144,
              max_score: 1440,
              arrows_per_end: 6,
              distance_1: "70m",
              face_1: 122,
              ends_1: 6,
              distance_2: "60m",
              face_2: 122,
              ends_2: 6,
              distance_3: "50m",
              face_3: 80,
              ends_3: 6,
              distance_4: "30m",
              face_4: 80,
              ends_4: 6,
              gmb_achievable: all_ladies_categories,
              mb_achievable: under_18_categories + adult_ladies_categories,
              bowman_achievable: under_18_categories + adult_ladies_categories,
              first_achievable: all_categories,
              second_achievable: all_categories,
              third_achievable: all_categories)

Round.create!(name: "Metric 2",
              indoor: false,
              organisation: "World Archery",
              max_hits: 144,
              max_score: 1440,
              arrows_per_end: 6,
              distance_1: "60m",
              face_1: 122,
              ends_1: 6,
              distance_2: "50m",
              face_2: 122,
              ends_2: 6,
              distance_3: "40m",
              face_3: 80,
              ends_3: 6,
              distance_4: "30m",
              face_4: 80,
              ends_4: 6,
              mb_achievable: under_16_categories + under_18_ladies,
              bowman_achievable: under_16_categories + under_18_ladies + adult_ladies_categories,
              first_achievable: all_categories,
              second_achievable: all_categories,
              third_achievable: all_categories)

Round.create!(name: "Metric 3",
              indoor: false,
              organisation: "World Archery",
              max_hits: 144,
              max_score: 1440,
              arrows_per_end: 6,
              distance_1: "50m",
              face_1: 122,
              ends_1: 6,
              distance_2: "40m",
              face_2: 122,
              ends_2: 6,
              distance_3: "30m",
              face_3: 80,
              ends_3: 6,
              distance_4: "20m",
              face_4: 80,
              ends_4: 6,
              mb_achievable: under_14_categories + under_16_ladies,
              bowman_achievable: under_14_categories + under_16_ladies,
              first_achievable: under_16_categories + under_18_ladies,
              second_achievable: under_18_categories + adult_ladies_categories,
              third_achievable: all_categories)

Round.create!(name: "Metric 4",
              indoor: false,
              organisation: "World Archery",
              max_hits: 144,
              max_score: 1440,
              arrows_per_end: 6,
              distance_1: "40m",
              face_1: 122,
              ends_1: 6,
              distance_2: "30m",
              face_2: 122,
              ends_2: 6,
              distance_3: "20m",
              face_3: 80,
              ends_3: 6,
              distance_4: "10m",
              face_4: 80,
              ends_4: 6,
              mb_achievable: under_12_categories + under_14_ladies,
              bowman_achievable: under_12_categories + under_14_ladies,
              first_achievable: under_14_categories + under_16_ladies,
              second_achievable: under_16_categories + under_18_ladies,
              third_achievable: under_18_categories + adult_ladies_categories)

Round.create!(name: "Metric 5",
              indoor: false,
              organisation: "World Archery",
              max_hits: 144,
              max_score: 1440,
              arrows_per_end: 6,
              distance_1: "30m",
              face_1: 122,
              ends_1: 6,
              distance_2: "20m",
              face_2: 122,
              ends_2: 6,
              distance_3: "15m",
              face_3: 80,
              ends_3: 6,
              distance_4: "10m",
              face_4: 80,
              ends_4: 6,
              mb_achievable: under_12_ladies,
              bowman_achievable: under_12_ladies,
              first_achievable: under_12_categories + under_14_ladies,
              second_achievable: under_14_categories + under_16_ladies,
              third_achievable: under_16_categories + under_18_ladies)

Round.create!(name: "Long Metric (Gentlemen)",
              indoor: false,
              organisation: "World Archery",
              max_hits: 72,
              max_score: 720,
              arrows_per_end: 6,
              distance_1: "90m",
              face_1: 122,
              ends_1: 6,
              distance_2: "70m",
              face_2: 122,
              ends_2: 6,
              bowman_achievable: all_categories,
              first_achievable: all_categories,
              second_achievable: all_categories,
              third_achievable: all_categories)

Round.create!(name: "Long Metric (Ladies)",
              indoor: false,
              organisation: "World Archery",
              max_hits: 72,
              max_score: 720,
              arrows_per_end: 6,
              distance_1: "70m",
              face_1: 122,
              ends_1: 6,
              distance_2: "60m",
              face_2: 122,
              ends_2: 6,
              bowman_achievable: under_18_categories + adult_ladies_categories,
              first_achievable: all_categories,
              second_achievable: all_categories,
              third_achievable: all_categories)

Round.create!(name: "Long Metric 1",
              indoor: false,
              organisation: "World Archery",
              max_hits: 72,
              max_score: 720,
              arrows_per_end: 6,
              distance_1: "70m",
              face_1: 122,
              ends_1: 6,
              distance_2: "60m",
              face_2: 122,
              ends_2: 6,
              bowman_achievable: under_18_categories + adult_ladies_categories,
              first_achievable: all_categories,
              second_achievable: all_categories,
              third_achievable: all_categories)

Round.create!(name: "Long Metric 2",
              indoor: false,
              organisation: "World Archery",
              max_hits: 72,
              max_score: 720,
              arrows_per_end: 6,
              distance_1: "60m",
              face_1: 122,
              ends_1: 6,
              distance_2: "50m",
              face_2: 122,
              ends_2: 6,
              bowman_achievable: under_16_categories + under_18_ladies + adult_ladies_categories,
              first_achievable: all_categories,
              second_achievable: all_categories,
              third_achievable: all_categories)

Round.create!(name: "Long Metric 3",
              indoor: false,
              organisation: "World Archery",
              max_hits: 72,
              max_score: 720,
              arrows_per_end: 6,
              distance_1: "50m",
              face_1: 122,
              ends_1: 6,
              distance_2: "40m",
              face_2: 122,
              ends_2: 6,
              bowman_achievable: under_14_categories + under_16_ladies,
              first_achievable: under_16_categories + under_18_ladies,
              second_achievable: under_18_categories + adult_ladies_categories,
              third_achievable: all_categories)

Round.create!(name: "Long Metric 4",
              indoor: false,
              organisation: "World Archery",
              max_hits: 72,
              max_score: 720,
              arrows_per_end: 6,
              distance_1: "40m",
              face_1: 122,
              ends_1: 6,
              distance_2: "30m",
              face_2: 122,
              ends_2: 6,
              bowman_achievable: under_12_categories + under_14_ladies,
              first_achievable: under_14_categories + under_16_ladies,
              second_achievable: under_16_categories + under_18_ladies,
              third_achievable: under_18_categories + adult_ladies_categories)

Round.create!(name: "Long Metric 5",
              indoor: false,
              organisation: "World Archery",
              max_hits: 72,
              max_score: 720,
              arrows_per_end: 6,
              distance_1: "30m",
              face_1: 122,
              ends_1: 6,
              distance_2: "20m",
              face_2: 122,
              ends_2: 6,
              bowman_achievable: under_12_ladies,
              first_achievable: under_12_categories + under_14_ladies,
              second_achievable: under_14_categories + under_16_ladies,
              third_achievable: under_16_categories + under_18_ladies)

Round.create!(name: "Short Metric 1",
              indoor: false,
              organisation: "World Archery",
              max_hits: 72,
              max_score: 720,
              arrows_per_end: 6,
              distance_1: "50m",
              face_1: 122,
              ends_1: 6,
              distance_2: "30m",
              face_2: 122,
              ends_2: 6,
              bowman_achievable: under_14_categories + under_16_ladies,
              first_achievable: under_16_categories + under_18_ladies,
              second_achievable: under_18_categories + adult_ladies_categories,
              third_achievable: all_categories)

Round.create!(name: "Short Metric 2",
              indoor: false,
              organisation: "World Archery",
              max_hits: 72,
              max_score: 720,
              arrows_per_end: 6,
              distance_1: "40m",
              face_1: 122,
              ends_1: 6,
              distance_2: "30m",
              face_2: 122,
              ends_2: 6,
              bowman_achievable: under_12_categories + under_14_ladies,
              first_achievable: under_14_categories + under_16_ladies,
              second_achievable: under_16_categories + under_18_ladies,
              third_achievable: under_18_categories + adult_ladies_categories)

Round.create!(name: "Short Metric 3",
              indoor: false,
              organisation: "World Archery",
              max_hits: 72,
              max_score: 720,
              arrows_per_end: 6,
              distance_1: "30m",
              face_1: 122,
              ends_1: 6,
              distance_2: "20m",
              face_2: 122,
              ends_2: 6,
              bowman_achievable: under_12_ladies,
              first_achievable: under_12_categories + under_14_ladies,
              second_achievable: under_14_categories + under_16_ladies,
              third_achievable: under_16_categories + under_18_ladies)

Round.create!(name: "Short Metric 4",
              indoor: false,
              organisation: "World Archery",
              max_hits: 72,
              max_score: 720,
              arrows_per_end: 6,
              distance_1: "20m",
              face_1: 122,
              ends_1: 6,
              distance_2: "10m",
              face_2: 122,
              ends_2: 6,
              first_achievable: under_12_ladies,
              second_achievable: under_12_categories + under_14_ladies,
              third_achievable: under_14_categories + under_16_ladies)

Round.create!(name: "Short Metric 5",
              indoor: false,
              organisation: "World Archery",
              max_hits: 72,
              max_score: 720,
              arrows_per_end: 6,
              distance_1: "15m",
              face_1: 122,
              ends_1: 6,
              distance_2: "10m",
              face_2: 122,
              ends_2: 6,
              second_achievable: under_12_ladies,
              third_achievable: under_12_categories + under_14_ladies)
              
Round.create!(name: "Half WA (Gentlemen)",
              indoor: false,
              organisation: "World Archery",
              max_hits: 72,
              max_score: 720,
              arrows_per_end: 6,
              distance_1: "90m",
              face_1: 122,
              ends_1: 3,
              distance_2: "70m",
              face_2: 122,
              ends_2: 3,
              distance_3: "50m",
              face_3: 80,
              ends_3: 3,
              distance_4: "30m",
              face_4: 80,
              ends_4: 3)

Round.create!(name: "Half WA (Ladies)",
              indoor: false,
              organisation: "World Archery",
              max_hits: 72,
              max_score: 720,
              arrows_per_end: 6,
              distance_1: "70m",
              face_1: 122,
              ends_1: 3,
              distance_2: "60m",
              face_2: 122,
              ends_2: 3,
              distance_3: "50m",
              face_3: 80,
              ends_3: 3,
              distance_4: "30m",
              face_4: 80,
              ends_4: 3)

Round.create!(name: "Half Metric 1",
              indoor: false,
              organisation: "World Archery",
              max_hits: 72,
              max_score: 720,
              arrows_per_end: 6,
              distance_1: "70m",
              face_1: 122,
              ends_1: 3,
              distance_2: "60m",
              face_2: 122,
              ends_2: 3,
              distance_3: "50m",
              face_3: 80,
              ends_3: 3,
              distance_4: "30m",
              face_4: 80,
              ends_4: 3)

Round.create!(name: "Half Metric 2",
              indoor: false,
              organisation: "World Archery",
              max_hits: 72,
              max_score: 720,
              arrows_per_end: 6,
              distance_1: "60m",
              face_1: 122,
              ends_1: 3,
              distance_2: "50m",
              face_2: 122,
              ends_2: 3,
              distance_3: "40m",
              face_3: 80,
              ends_3: 3,
              distance_4: "30m",
              face_4: 80,
              ends_4: 3)

Round.create!(name: "Half Metric 3",
              indoor: false,
              organisation: "World Archery",
              max_hits: 72,
              max_score: 720,
              arrows_per_end: 6,
              distance_1: "50m",
              face_1: 122,
              ends_1: 3,
              distance_2: "40m",
              face_2: 122,
              ends_2: 3,
              distance_3: "30m",
              face_3: 80,
              ends_3: 3,
              distance_4: "20m",
              face_4: 80,
              ends_4: 3)

Round.create!(name: "Half Metric 4",
              indoor: false,
              organisation: "World Archery",
              max_hits: 72,
              max_score: 720,
              arrows_per_end: 6,
              distance_1: "40m",
              face_1: 122,
              ends_1: 3,
              distance_2: "30m",
              face_2: 122,
              ends_2: 3,
              distance_3: "20m",
              face_3: 80,
              ends_3: 3,
              distance_4: "10m",
              face_4: 80,
              ends_4: 3)

Round.create!(name: "Half Metric 5",
              indoor: false,
              organisation: "World Archery",
              max_hits: 72,
              max_score: 720,
              arrows_per_end: 6,
              distance_1: "30m",
              face_1: 122,
              ends_1: 3,
              distance_2: "20m",
              face_2: 122,
              ends_2: 3,
              distance_3: "15m",
              face_3: 80,
              ends_3: 3,
              distance_4: "10m",
              face_4: 80,
              ends_4: 3)

Round.create!(name: "WA 900",
              indoor: false,
              organisation: "World Archery",
              max_hits: 90,
              max_score: 900,
              arrows_per_end: 6,
              distance_1: "60m",
              face_1: 122,
              ends_1: 5,
              distance_2: "50m",
              face_2: 122,
              ends_2: 5,
              distance_3: "40m",
              face_3: 122,
              ends_3: 5,
              bowman_achievable: under_16_categories + under_18_ladies,
              first_achievable: under_18_categories + adult_ladies_categories,
              second_achievable: all_categories,
              third_achievable: all_categories)

Round.create!(name: "WA 70m",
              indoor: false,
              organisation: "World Archery",
              max_hits: 72,
              max_score: 720,
              arrows_per_end: 6,
              distance_1: "70m",
              face_1: 122,
              ends_1: 12,
              bowman_achievable: under_18_categories + adult_ladies_categories,
              first_achievable: all_categories,
              second_achievable: all_categories,
              third_achievable: all_categories)

Round.create!(name: "WA 60m",
              indoor: false,
              organisation: "World Archery",
              max_hits: 72,
              max_score: 720,
              arrows_per_end: 6,
              distance_1: "60m",
              face_1: 122,
              ends_1: 12,
              bowman_achievable: under_16_categories + under_18_ladies,
              first_achievable: under_18_categories + adult_ladies_categories,
              second_achievable: all_categories,
              third_achievable: all_categories)

Round.create!(name: "WA 50m",
              indoor: false,
              organisation: "World Archery",
              max_hits: 72,
              max_score: 720,
              arrows_per_end: 6,
              distance_1: "50m",
              face_1: 80,
              ends_1: 12,
              bowman_achievable: under_14_categories + under_16_ladies,
              first_achievable: under_16_categories + under_18_ladies,
              second_achievable: under_18_categories + adult_ladies_categories,
              third_achievable: all_categories)
  
Round.create!(name: "WA Standard",
              indoor: false,
              organisation: "World Archery",
              max_hits: 72,
              max_score: 720,
              arrows_per_end: 6,
              distance_1: "50m",
              face_1: 122,
              ends_1: 6,
              distance_2: "30m",
              face_2: 122,
              ends_2: 6)
              
Round.create!(name: "Frostbite",
              indoor: false,
              organisation: "World Archery",
              max_hits: 36,
              max_score: 360,
              arrows_per_end: 6,
              distance_1: "30m",
              face_1: 80,
              ends_1: 6)

# =============== WA indoor =============== #
Round.create!(name: "WA 18m (Full-size face)",
              indoor: true,
              bowstyle: "Non Compound",
              organisation: "World Archery",
              max_hits: 60,
              max_score: 600,
              arrows_per_end: 3,
              distance_1: "18m",
              face_1: 40,
              ends_1: 20)
 
Round.create!(name: "WA 18m (Triple faces)",
              indoor: true,
              bowstyle: "Non Compound",
              organisation: "World Archery",
              max_hits: 60,
              max_score: 600,
              arrows_per_end: 3,
              distance_1: "18m",
              face_1: 40,
              ends_1: 20)
 
Round.create!(name: "WA 18m (Full-size face)",
              indoor: true,
              bowstyle: "Compound",
              organisation: "World Archery",
              max_hits: 60,
              max_score: 600,
              arrows_per_end: 3,
              distance_1: "18m",
              face_1: 40,
              ends_1: 20)
 
Round.create!(name: "WA 18m (Triple faces)",
              indoor: true,
              bowstyle: "Compound",
              organisation: "World Archery",
              max_hits: 60,
              max_score: 600,
              arrows_per_end: 3,
              distance_1: "18m",
              face_1: 40,
              ends_1: 20)
 
Round.create!(name: "WA 25m (Full-size face)",
              indoor: true,
              bowstyle: "Non Compound",
              organisation: "World Archery",
              max_hits: 60,
              max_score: 600,
              arrows_per_end: 3,
              distance_1: "25m",
              face_1: 60,
              ends_1: 20)
 
Round.create!(name: "WA 25m (Triple faces)",
              indoor: true,
              bowstyle: "Non Compound",
              organisation: "World Archery",
              max_hits: 60,
              max_score: 600,
              arrows_per_end: 3,
              distance_1: "25m",
              face_1: 60,
              ends_1: 20) 
              
Round.create!(name: "WA 25m (Full-size face)",
              indoor: true,
              bowstyle: "Compound",
              organisation: "World Archery",
              max_hits: 60,
              max_score: 600,
              arrows_per_end: 3,
              distance_1: "25m",
              face_1: 60,
              ends_1: 20)
 
Round.create!(name: "WA 25m (Triple faces)",
              indoor: true,
              bowstyle: "Compound",
              organisation: "World Archery",
              max_hits: 60,
              max_score: 600,
              arrows_per_end: 3,
              distance_1: "25m",
              face_1: 60,
              ends_1: 20)
 
Round.create!(name: "WA Combined (Full-size face)",
              indoor: true,
              bowstyle: "Non Compound",
              organisation: "World Archery",
              max_hits: 120,
              max_score: 1200,
              arrows_per_end: 3,
              distance_1: "25m",
              face_1: 60,
              ends_1: 20,
              distance_2: "18m",
              face_2: 40,
              ends_2: 20)
  
Round.create!(name: "WA Combined (Triple face)",
              indoor: true,
              bowstyle: "Non Compound",
              organisation: "World Archery",
              max_hits: 120,
              max_score: 1200,
              arrows_per_end: 3,
              distance_1: "25m",
              face_1: 60,
              ends_1: 20,
              distance_2: "18m",
              face_2: 40,
              ends_2: 20)
  
Round.create!(name: "WA Combined (Full-size face)",
              indoor: true,
              bowstyle: "Compound",
              organisation: "World Archery",
              max_hits: 120,
              max_score: 1200,
              arrows_per_end: 3,
              distance_1: "25m",
              face_1: 60,
              ends_1: 20,
              distance_2: "18m",
              face_2: 40,
              ends_2: 20)
  
Round.create!(name: "WA Combined (Triple face)",
              indoor: true,
              bowstyle: "Compound",
              organisation: "World Archery",
              max_hits: 120,
              max_score: 1200,
              arrows_per_end: 3,
              distance_1: "25m",
              face_1: 60,
              ends_1: 20,
              distance_2: "18m",
              face_2: 40,
              ends_2: 20)

Round.create!(name: "Vegas",
              indoor: true,
              bowstyle: "Non Compound",
              organisation: "World Archery",
              max_hits: 60,
              max_score: 600,
              arrows_per_end: 3,
              distance_1: "18m",
              face_1: 40,
              ends_1: 20,
              notes: "3 spot only")

Round.create!(name: "Vegas",
              indoor: true,
              bowstyle: "Compound",
              organisation: "World Archery",
              max_hits: 60,
              max_score: 600,
              arrows_per_end: 3,
              distance_1: "18m",
              face_1: 40,
              ends_1: 20,
              notes: "3 spot only")

# =========== Archery GB outdoor ========== #
Round.create!(name: "York",
              indoor: false,
              organisation: "Archery GB",
              max_hits: 144,
              max_score: 1296,
              arrows_per_end: 6,
              distance_1: "100yds",
              face_1: 122,
              ends_1: 12,
              distance_2: "80yds",
              face_2: 122,
              ends_2: 8,
              distance_3: "60yds",
              face_3: 122,
              ends_3: 4,
              gmb_achievable: all_categories,
              mb_achievable: all_categories,
              bowman_achievable: all_categories,
              first_achievable: all_categories,
              second_achievable: all_categories,
              third_achievable: all_categories)
              
Round.create!(name: "Hereford",
              indoor: false,
              organisation: "Archery GB",
              max_hits: 144,
              max_score: 1296,
              arrows_per_end: 6,
              distance_1: "80yds",
              face_1: 122,
              ends_1: 12,
              distance_2: "60yds",
              face_2: 122,
              ends_2: 8,
              distance_3: "50yds",
              face_3: 122,
              ends_3: 4,
              gmb_achievable: all_ladies_categories,
              mb_achievable: under_18_categories + adult_ladies_categories,
              bowman_achievable: under_18_categories + adult_ladies_categories,
              first_achievable: all_categories,
              second_achievable: all_categories,
              third_achievable: all_categories)
              
Round.create!(name: "Bristol 1",
              indoor: false,
              organisation: "Archery GB",
              max_hits: 144,
              max_score: 1296,
              arrows_per_end: 6,
              distance_1: "80yds",
              face_1: 122,
              ends_1: 12,
              distance_2: "60yds",
              face_2: 122,
              ends_2: 8,
              distance_3: "50yds",
              face_3: 122,
              ends_3: 4,
              gmb_achievable: all_ladies_categories,
              mb_achievable: under_18_categories + adult_ladies_categories,
              bowman_achievable: under_18_categories + adult_ladies_categories,
              first_achievable: all_categories,
              second_achievable: all_categories,
              third_achievable: all_categories)
              
Round.create!(name: "Bristol 2",
              indoor: false,
              organisation: "Archery GB",
              max_hits: 144,
              max_score: 1296,
              arrows_per_end: 6,
              distance_1: "60yds",
              face_1: 122,
              ends_1: 12,
              distance_2: "50yds",
              face_2: 122,
              ends_2: 8,
              distance_3: "40yds",
              face_3: 122,
              ends_3: 4,
              mb_achievable: under_16_categories + under_18_ladies,
              bowman_achievable: under_16_categories + under_18_ladies + adult_ladies_categories,
              first_achievable: all_categories,
              second_achievable: all_categories,
              third_achievable: all_categories)
  
Round.create!(name: "Bristol 3",
              indoor: false,
              organisation: "Archery GB",
              max_hits: 144,
              max_score: 1296,
              arrows_per_end: 6,
              distance_1: "50yds",
              face_1: 122,
              ends_1: 12,
              distance_2: "40yds",
              face_2: 122,
              ends_2: 8,
              distance_3: "30yds",
              face_3: 122,
              ends_3: 4,
              mb_achievable: under_14_categories + under_16_ladies,
              bowman_achievable: under_14_categories + under_16_ladies,
              first_achievable: under_16_categories + under_18_ladies,
              second_achievable: under_18_categories + adult_ladies_categories,
              third_achievable: all_categories)

Round.create!(name: "Bristol 4",
              indoor: false,
              organisation: "Archery GB",
              max_hits: 144,
              max_score: 1296,
              arrows_per_end: 6,
              distance_1: "40yds",
              face_1: 122,
              ends_1: 12,
              distance_2: "30yds",
              face_2: 122,
              ends_2: 8,
              distance_3: "20yds",
              face_3: 122,
              ends_3: 4,
              mb_achievable: under_12_categories + under_14_ladies,
              bowman_achievable: under_12_categories + under_14_ladies,
              first_achievable: under_14_categories + under_16_ladies,
              second_achievable: under_16_categories + under_18_ladies,
              third_achievable: under_18_categories + adult_ladies_categories)

Round.create!(name: "Bristol 5",
              indoor: false,
              organisation: "Archery GB",
              max_hits: 144,
              max_score: 1296,
              arrows_per_end: 6,
              distance_1: "30yds",
              face_1: 122,
              ends_1: 12,
              distance_2: "20yds",
              face_2: 122,
              ends_2: 8,
              distance_3: "10yds",
              face_3: 122,
              ends_3: 4,
              mb_achievable: under_12_ladies,
              bowman_achievable: under_12_ladies,
              first_achievable: under_12_categories + under_14_ladies,
              second_achievable: under_14_categories + under_16_ladies,
              third_achievable: under_16_categories + under_18_ladies)

Round.create!(name: "New National",
              indoor: false,
              organisation: "Archery GB",
              max_hits: 72,
              max_score: 648,
              arrows_per_end: 6,
              distance_1: "100yds",
              face_1: 122,
              ends_1: 8,
              distance_2: "80yds",
              face_2: 122,
              ends_2: 4,
              bowman_achievable: all_categories,
              first_achievable: all_categories,
              second_achievable: all_categories,
              third_achievable: all_categories)
              
Round.create!(name: "Long National",
              indoor: false,
              organisation: "Archery GB",
              max_hits: 72,
              max_score: 648,
              arrows_per_end: 6,
              distance_1: "80yds",
              face_1: 122,
              ends_1: 8,
              distance_2: "60yds",
              face_2: 122,
              ends_2: 4,
              bowman_achievable: under_18_categories + adult_ladies_categories,
              first_achievable: all_categories,
              second_achievable: all_categories,
              third_achievable: all_categories)
              
Round.create!(name: "National",
              indoor: false,
              organisation: "Archery GB",
              max_hits: 72,
              max_score: 648,
              arrows_per_end: 6,
              distance_1: "60yds",
              face_1: 122,
              ends_1: 8,
              distance_2: "50yds",
              face_2: 122,
              ends_2: 4,
              bowman_achievable: under_16_categories + under_18_ladies,
              first_achievable: under_18_categories + adult_ladies_categories,
              second_achievable: all_categories,
              third_achievable: all_categories)
              
Round.create!(name: "Short National",
              indoor: false,
              organisation: "Archery GB",
              max_hits: 72,
              max_score: 648,
              arrows_per_end: 6,
              distance_1: "50yds",
              face_1: 122,
              ends_1: 8,
              distance_2: "40yds",
              face_2: 122,
              ends_2: 4,
              bowman_achievable: under_14_categories + under_16_ladies,
              first_achievable: under_16_categories + under_18_ladies,
              second_achievable: under_18_categories + adult_ladies_categories,
              third_achievable: all_categories)
              
Round.create!(name: "Junior National",
              indoor: false,
              organisation: "Archery GB",
              max_hits: 72,
              max_score: 648,
              arrows_per_end: 6,
              distance_1: "40yds",
              face_1: 122,
              ends_1: 8,
              distance_2: "30yds",
              face_2: 122,
              ends_2: 4,
              bowman_achievable: under_12_categories + under_14_ladies,
              first_achievable: under_14_categories + under_16_ladies,
              second_achievable: under_16_categories + under_18_ladies,
              third_achievable: under_18_categories + adult_ladies_categories)
              
Round.create!(name: "Short Junior National",
              indoor: false,
              organisation: "Archery GB",
              max_hits: 72,
              max_score: 648,
              arrows_per_end: 6,
              distance_1: "30yds",
              face_1: 122,
              ends_1: 8,
              distance_2: "20yds",
              face_2: 122,
              ends_2: 4,
              bowman_achievable: under_12_ladies,
              first_achievable: under_12_categories + under_14_ladies,
              second_achievable: under_14_categories + under_16_ladies,
              third_achievable: under_16_categories + under_18_ladies)
              
Round.create!(name: "New Warwick",
              indoor: false,
              organisation: "Archery GB",
              max_hits: 48,
              max_score: 432,
              arrows_per_end: 6,
              distance_1: "100yds",
              face_1: 122,
              ends_1: 4,
              distance_2: "80yds",
              face_2: 122,
              ends_2: 4,
              second_achievable: all_categories,
              third_achievable: all_categories)
              
Round.create!(name: "Long Warwick",
              indoor: false,
              organisation: "Archery GB",
              max_hits: 48,
              max_score: 432,
              arrows_per_end: 6,
              distance_1: "80yds",
              face_1: 122,
              ends_1: 4,
              distance_2: "60yds",
              face_2: 122,
              ends_2: 4,
              second_achievable: all_categories,
              third_achievable: all_categories)
              
Round.create!(name: "Warwick",
              indoor: false,
              organisation: "Archery GB",
              max_hits: 48,
              max_score: 432,
              arrows_per_end: 6,
              distance_1: "60yds",
              face_1: 122,
              ends_1: 4,
              distance_2: "50yds",
              face_2: 122,
              ends_2: 4,
              second_achievable: all_categories,
              third_achievable: all_categories)
              
Round.create!(name: "Short Warwick",
              indoor: false,
              organisation: "Archery GB",
              max_hits: 48,
              max_score: 432,
              arrows_per_end: 6,
              distance_1: "50yds",
              face_1: 122,
              ends_1: 4,
              distance_2: "40yds",
              face_2: 122,
              ends_2: 4,
              second_achievable: under_18_categories + adult_ladies_categories,
              third_achievable: all_categories)
              
Round.create!(name: "Junior Warwick",
              indoor: false,
              organisation: "Archery GB",
              max_hits: 48,
              max_score: 432,
              arrows_per_end: 6,
              distance_1: "40yds",
              face_1: 122,
              ends_1: 4,
              distance_2: "30yds",
              face_2: 122,
              ends_2: 4,
              second_achievable: under_16_categories + under_18_ladies,
              third_achievable: under_18_categories + adult_ladies_categories)
              
Round.create!(name: "Short Junior Warwick",
              indoor: false,
              organisation: "Archery GB",
              max_hits: 48,
              max_score: 432,
              arrows_per_end: 6,
              distance_1: "30yds",
              face_1: 122,
              ends_1: 4,
              distance_2: "20yds",
              face_2: 122,
              ends_2: 4,
              second_achievable: under_14_categories + under_16_ladies,
              third_achievable: under_18_categories + adult_ladies_categories)
              
Round.create!(name: "New Western",
              indoor: false,
              organisation: "Archery GB",
              max_hits: 96,
              max_score: 864,
              arrows_per_end: 6,
              distance_1: "100yds",
              face_1: 122,
              ends_1: 8,
              distance_2: "80yds",
              face_2: 122,
              ends_2: 8,
              bowman_achievable: all_categories,
              first_achievable: all_categories,
              second_achievable: all_categories,
              third_achievable: all_categories)
              
Round.create!(name: "Long Western",
              indoor: false,
              organisation: "Archery GB",
              max_hits: 96,
              max_score: 864,
              arrows_per_end: 6,
              distance_1: "80yds",
              face_1: 122,
              ends_1: 8,
              distance_2: "60yds",
              face_2: 122,
              ends_2: 8,
              bowman_achievable: under_18_categories + adult_ladies_categories,
              first_achievable: all_categories,
              second_achievable: all_categories,
              third_achievable: all_categories)    
              
Round.create!(name: "Western",
              indoor: false,
              organisation: "Archery GB",
              max_hits: 96,
              max_score: 864,
              arrows_per_end: 6,
              distance_1: "60yds",
              face_1: 122,
              ends_1: 8,
              distance_2: "50yds",
              face_2: 122,
              ends_2: 8,
              bowman_achievable: under_16_categories + under_18_ladies,
              first_achievable: under_18_categories + adult_ladies_categories,
              second_achievable: all_categories,
              third_achievable: all_categories)
              
Round.create!(name: "Short Western",
              indoor: false,
              organisation: "Archery GB",
              max_hits: 96,
              max_score: 864,
              arrows_per_end: 6,
              distance_1: "50yds",
              face_1: 122,
              ends_1: 8,
              distance_2: "40yds",
              face_2: 122,
              ends_2: 8,
              bowman_achievable: under_14_categories + under_16_ladies,
              first_achievable: under_16_categories + under_18_ladies,
              second_achievable: under_18_categories + adult_ladies_categories,
              third_achievable: all_categories)

Round.create!(name: "Junior Western",
              indoor: false,
              organisation: "Archery GB",
              max_hits: 96,
              max_score: 864,
              arrows_per_end: 6,
              distance_1: "40yds",
              face_1: 122,
              ends_1: 8,
              distance_2: "30yds",
              face_2: 122,
              ends_2: 8,
              bowman_achievable: under_12_categories + under_14_ladies,
              first_achievable: under_14_categories + under_16_ladies,
              second_achievable: under_16_categories + under_18_ladies,
              third_achievable: under_18_categories + adult_ladies_categories)

Round.create!(name: "Short Junior Western",
              indoor: false,
              organisation: "Archery GB",
              max_hits: 96,
              max_score: 864,
              arrows_per_end: 6,
              distance_1: "30yds",
              face_1: 122,
              ends_1: 8,
              distance_2: "20yds",
              face_2: 122,
              ends_2: 8,
              bowman_achievable: under_12_ladies,
              first_achievable: under_12_categories + under_14_ladies,
              second_achievable: under_14_categories + under_16_ladies,
              third_achievable: under_16_categories + under_18_ladies)

Round.create!(name: "St George",
              indoor: false,
              organisation: "Archery GB",
              max_hits: 108,
              max_score: 972,
              arrows_per_end: 6,
              distance_1: "100yds",
              face_1: 122,
              ends_1: 6,
              distance_2: "80yds",
              face_2: 122,
              ends_2: 6,
              distance_3: "60yds",
              face_3: 122,
              ends_3: 6,
              bowman_achievable: all_categories,
              first_achievable: all_categories,
              second_achievable: all_categories,
              third_achievable: all_categories)

Round.create!(name: "Albion",
              indoor: false,
              organisation: "Archery GB",
              max_hits: 108,
              max_score: 972,
              arrows_per_end: 6,
              distance_1: "80yds",
              face_1: 122,
              ends_1: 6,
              distance_2: "60yds",
              face_2: 122,
              ends_2: 6,
              distance_3: "50yds",
              face_3: 122,
              ends_3: 6,
              bowman_achievable: under_18_categories + adult_ladies_categories,
              first_achievable: all_categories,
              second_achievable: all_categories,
              third_achievable: all_categories)

Round.create!(name: "Windsor",
              indoor: false,
              organisation: "Archery GB",
              max_hits: 108,
              max_score: 972,
              arrows_per_end: 6,
              distance_1: "60yds",
              face_1: 122,
              ends_1: 6,
              distance_2: "50yds",
              face_2: 122,
              ends_2: 6,
              distance_3: "40yds",
              face_3: 122,
              ends_3: 6,
              bowman_achievable: under_16_categories + under_18_ladies,
              first_achievable: under_18_categories + adult_ladies_categories,
              second_achievable: all_categories,
              third_achievable: all_categories)

Round.create!(name: "Short Windsor",
              indoor: false,
              organisation: "Archery GB",
              max_hits: 108,
              max_score: 972,
              arrows_per_end: 6,
              distance_1: "50yds",
              face_1: 122,
              ends_1: 6,
              distance_2: "40yds",
              face_2: 122,
              ends_2: 6,
              distance_3: "30yds",
              face_3: 122,
              ends_3: 6,
              bowman_achievable: under_14_categories + under_16_ladies,
              first_achievable: under_16_categories + under_18_ladies,
              second_achievable: under_18_categories + adult_ladies_categories,
              third_achievable: all_categories)

Round.create!(name: "Junior Windsor",
              indoor: false,
              organisation: "Archery GB",
              max_hits: 108,
              max_score: 972,
              arrows_per_end: 6,
              distance_1: "40yds",
              face_1: 122,
              ends_1: 6,
              distance_2: "30yds",
              face_2: 122,
              ends_2: 6,
              distance_3: "20yds",
              face_3: 122,
              ends_3: 6,
              bowman_achievable: under_12_categories + under_14_ladies,
              first_achievable: under_14_categories + under_16_ladies,
              second_achievable: under_16_categories + under_18_ladies,
              third_achievable: under_18_categories + adult_ladies_categories)

Round.create!(name: "Short Junior Windsor",
              indoor: false,
              organisation: "Archery GB",
              max_hits: 108,
              max_score: 972,
              arrows_per_end: 6,
              distance_1: "30yds",
              face_1: 122,
              ends_1: 6,
              distance_2: "20yds",
              face_2: 122,
              ends_2: 6,
              distance_3: "10yds",
              face_3: 122,
              ends_3: 6,
              bowman_achievable: under_12_ladies,
              first_achievable: under_12_categories + under_14_ladies,
              second_achievable: under_14_categories + under_16_ladies,
              third_achievable: under_16_categories + under_18_ladies)

Round.create!(name: "American",
              indoor: false,
              organisation: "Archery GB",
              max_hits: 90,
              max_score: 810,
              arrows_per_end: 6,
              distance_1: "60yds",
              face_1: 122,
              ends_1: 5,
              distance_2: "50yds",
              face_2: 122,
              ends_2: 5,
              distance_3: "40yds",
              face_3: 122,
              ends_3: 5,
              bowman_achievable: under_16_categories + under_18_ladies,
              first_achievable: under_18_categories + adult_ladies_categories,
              second_achievable: all_categories,
              third_achievable: all_categories)

Round.create!(name: "St Nicholas",
              indoor: false,
              organisation: "Archery GB",
              max_hits: 84,
              max_score: 756,
              arrows_per_end: 6,
              distance_1: "40yds",
              face_1: 122,
              ends_1: 8,
              distance_2: "30yds",
              face_2: 122,
              ends_2: 6,
              bowman_achievable: under_12_categories + under_14_ladies,
              first_achievable: under_14_categories + under_16_ladies,
              second_achievable: under_16_categories + under_18_ladies,
              third_achievable: under_18_categories + adult_ladies_categories)
              
# =========== Archery GB indoor =========== #
Round.create!(name: "Portsmouth (Full-size face)",
              indoor: true,
              bowstyle: "Non Compound",
              organisation: "Archery GB",
              max_hits: 60,
              max_score: 600,
              arrows_per_end: 3,
              distance_1: "20yds",
              face_1: 60,
              ends_1: 20)
 
Round.create!(name: "Portsmouth (Triple faces)",
              indoor: true,
              bowstyle: "Non Compound",
              organisation: "Archery GB",
              max_hits: 60,
              max_score: 600,
              arrows_per_end: 3,
              distance_1: "20yds",
              face_1: 60,
              ends_1: 20)

Round.create!(name: "Portsmouth (Full-size face)",
              indoor: true,
              bowstyle: "Compound",
              organisation: "Archery GB",
              max_hits: 60,
              max_score: 600,
              arrows_per_end: 3,
              distance_1: "20yds",
              face_1: 60,
              ends_1: 20)
 
Round.create!(name: "Portsmouth (Triple faces)",
              indoor: true,
              bowstyle: "Compound",
              organisation: "Archery GB",
              max_hits: 60,
              max_score: 600,
              arrows_per_end: 3,
              distance_1: "20yds",
              face_1: 60,
              ends_1: 20)
 
Round.create!(name: "Bray I",
              indoor: true,
              bowstyle: "Non Compound",
              organisation: "Archery GB",
              max_hits: 30,
              max_score: 300,
              arrows_per_end: 3,
              distance_1: "20yds",
              face_1: 40,
              ends_1: 10)
              
Round.create!(name: "Bray II",
              indoor: true,
              bowstyle: "Non Compound",
              organisation: "Archery GB",
              max_hits: 30,
              max_score: 300,
              arrows_per_end: 3,
              distance_1: "25yds",
              face_1: 60,
              ends_1: 10)
  
Round.create!(name: "Bray I",
              indoor: true,
              bowstyle: "Compound",
              organisation: "Archery GB",
              max_hits: 30,
              max_score: 300,
              arrows_per_end: 3,
              distance_1: "20yds",
              face_1: 40,
              ends_1: 10)
              
Round.create!(name: "Bray II",
              indoor: true,
              bowstyle: "Compound",
              organisation: "Archery GB",
              max_hits: 30,
              max_score: 300,
              arrows_per_end: 3,
              distance_1: "25yds",
              face_1: 60,
              ends_1: 10)
              
Round.create!(name: "Stafford",
              indoor: true,
              bowstyle: "Non Compound",
              organisation: "Archery GB",
              max_hits: 60,
              max_score: 600,
              arrows_per_end: 3,
              distance_1: "30m",
              face_1: 80,
              ends_1: 20)
 
Round.create!(name: "Stafford",
              indoor: true,
              bowstyle: "Compound",
              organisation: "Archery GB",
              max_hits: 60,
              max_score: 600,
              arrows_per_end: 3,
              distance_1: "30m",
              face_1: 80,
              ends_1: 20)
              
Round.create!(name: "Worcester",
              indoor: true,
              organisation: "Archery GB",
              max_hits: 60,
              max_score: 300,
              arrows_per_end: 5,
              distance_1: "25yds",
              face_1: 40,
              ends_1: 12,
              notes: "First detail shoots at the top face, second detail shoots at the bottom face. After 6 ends details swap. Target face is 16 inch black and white with 5 scoring zones.")
