Score.create!(score: 1228, 
              hits: 144, 
              golds: 111, 
              round_id: 47, 
              bowtype: "Compound",
              user_id: 1, 
              name: "Emlyn Jones", 
              date: DateTime.parse("12/08/2017"), 
              location: "Meopham School Field",
              handicap: 14, 
              classification: "Master Bowman", 
              home: true, 
              club_record: true, 
              validated: true)